# Generated by Django 5.1 on 2024-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='image_or_video',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
