# Generated by Django 5.1 on 2024-08-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='main_interest',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
