# Generated by Django 5.1 on 2024-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_main_interest_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
