# Generated by Django 5.1 on 2024-08-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('profiles', '0003_profile_main_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='main_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.category'),
        ),
    ]
