# Generated by Django 3.2.25 on 2024-08-15 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestcircle',
            name='members',
            field=models.ManyToManyField(related_name='circles', to=settings.AUTH_USER_MODEL),
        ),
    ]
