# Generated by Django 3.2.25 on 2024-08-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='owner',
        ),
    ]
